language: python
python:
  - "3.10"
env:
  - WAGTAIL="wagtail>=2.16,<3.0" DB=sqlite
matrix:
  include:
  # Latest Wagtail version
  - env: WAGTAIL="wagtail>=2.16,<3.0" DB=postgres
  - env: WAGTAIL="wagtail>=2.16,<3.0" DB=mysql
  - python: "3.10"
  - python: "3.9"
  - python: "3.8"
  - python: "3.7"
  - python: "3.6"
  # Past Wagtail versions
  - python: "3.10"
    env: WAGTAIL="wagtail>=2.15,<2.16"
  - python: "3.8"
    env: WAGTAIL="wagtail>=2.11,<2.12"
  - python: "3.8"
    env: WAGTAIL="wagtail>=2.7,<2.8"
  - python: "3.6"
    env: WAGTAIL="wagtail>=2.3,<2.4"
  - python: "3.6"
    env: WAGTAIL="wagtail>=2.0,<2.1"
services:
  - mysql
  - postgresql
addons:
  postgresql: "13"
before_script:
  - mysql -e 'create database wagtail_modeltranslation;'
  - psql -c 'create database wagtail_modeltranslation;' -U postgres
install:
  - pip install --upgrade -q pip setuptools
  - if [[ $DB == mysql ]] && [[ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]]; then pip install -q mysql-python; elif [[ $DB == mysql ]] && [[ ${TRAVIS_PYTHON_VERSION:0:1} == "3" ]]; then pip install -q mysqlclient; fi
  - if [[ $DB == postgres ]]; then pip install -q 'psycopg2-binary'; fi
  - pip install $WAGTAIL
  - pip install -e .
script:
  - echo "DJANGO VERSION = `python -m django --version`"
  - ./runtests.py
